version: "3.8"
services:
  robot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    privileged: true
    network_mode: host
    pids_limit: -1
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/workspaces/FaceLock
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
    stdin_open: true
    # command: sleep infinity
    command: /bin/bash -c "cd /workspaces/FaceLock && git pull && colcon build && source install/setup.bash && ros2 launch face_lock startup.launch.py"
